/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.temperatureconverter;

/**
 *
 * @author aalok
 */
public class TempConv extends javax.swing.JFrame {

    /**
     * Creates new form TempConv
     */
    public TempConv() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txttemp = new javax.swing.JTextField();
        btnCtoF = new javax.swing.JButton();
        btnFtoC = new javax.swing.JButton();
        btnFtoC1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblres = new javax.swing.JLabel();
        btnKtoC = new javax.swing.JButton();
        btnCtoK = new javax.swing.JButton();
        btnFtoK = new javax.swing.JButton();
        btnKtoF = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabel1.setText("Temperature Converter");

        txttemp.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N

        btnCtoF.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        btnCtoF.setText("C to F");
        btnCtoF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCtoFActionPerformed(evt);
            }
        });

        btnFtoC.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        btnFtoC.setText("F to C");
        btnFtoC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFtoCActionPerformed(evt);
            }
        });

        btnFtoC1.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        btnFtoC1.setText("CLEAR");
        btnFtoC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFtoC1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel2.setText("RESULT:");

        lblres.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        lblres.setText("Temperature");

        btnKtoC.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        btnKtoC.setText("K to C");
        btnKtoC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKtoCActionPerformed(evt);
            }
        });

        btnCtoK.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        btnCtoK.setText("C to K");
        btnCtoK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCtoKActionPerformed(evt);
            }
        });

        btnFtoK.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        btnFtoK.setText("F to K");
        btnFtoK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFtoKActionPerformed(evt);
            }
        });

        btnKtoF.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        btnKtoF.setText("K to F");
        btnKtoF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKtoFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(102, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(106, 106, 106))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txttemp, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(btnCtoK)
                                            .addComponent(btnCtoF))
                                        .addGap(50, 50, 50))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(btnFtoC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnFtoK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnFtoC1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnKtoC, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(btnKtoF, javax.swing.GroupLayout.Alignment.TRAILING)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblres, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(80, 80, 80))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txttemp, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCtoF)
                    .addComponent(btnFtoC)
                    .addComponent(btnKtoC))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFtoK)
                    .addComponent(btnCtoK)
                    .addComponent(btnKtoF))
                .addGap(26, 26, 26)
                .addComponent(btnFtoC1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblres, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCtoFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCtoFActionPerformed
        double c=0.0d,f=0.0d;
        c=Double.parseDouble(txttemp.getText());
        f=9.0/5.0*(c)+32;
        lblres.setText(""+f);
    }//GEN-LAST:event_btnCtoFActionPerformed

    private void btnFtoCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFtoCActionPerformed
        double c,f;
        f=Double.parseDouble(txttemp.getText());
        c=(f-32)*5.0/9.0;
        lblres.setText(""+c);
    }//GEN-LAST:event_btnFtoCActionPerformed

    private void btnFtoC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFtoC1ActionPerformed
        txttemp.setText("");
        lblres.setText("");
    }//GEN-LAST:event_btnFtoC1ActionPerformed

    private void btnKtoCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKtoCActionPerformed
        double k,c;
        k=Double.parseDouble(txttemp.getText());
        c=k-273;
        lblres.setText(""+c);
    }//GEN-LAST:event_btnKtoCActionPerformed

    private void btnCtoKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCtoKActionPerformed
        double k,c;
        c=Double.parseDouble(txttemp.getText());
        k=c+273;
        lblres.setText(""+k);
    }//GEN-LAST:event_btnCtoKActionPerformed

    private void btnFtoKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFtoKActionPerformed
        double f,k;
        f=Double.parseDouble(txttemp.getText());
        k=(f-32)*5.0/9.0+273;
        lblres.setText(""+k);
    }//GEN-LAST:event_btnFtoKActionPerformed

    private void btnKtoFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKtoFActionPerformed
        double f,k;
        k=Double.parseDouble(txttemp.getText());
        f=9.0/5.0*(k-273)+32;
        lblres.setText(""+f);
    }//GEN-LAST:event_btnKtoFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TempConv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TempConv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TempConv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TempConv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TempConv().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCtoF;
    private javax.swing.JButton btnCtoK;
    private javax.swing.JButton btnFtoC;
    private javax.swing.JButton btnFtoC1;
    private javax.swing.JButton btnFtoK;
    private javax.swing.JButton btnKtoC;
    private javax.swing.JButton btnKtoF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblres;
    private javax.swing.JTextField txttemp;
    // End of variables declaration//GEN-END:variables
}
